import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS

// Send POST request using data-driven variables
def postResponse = WS.sendRequest(findTestObject(
	'usingdata/postpetdata',
	[
		('id') : id,
		('name') : name,
		('status') : status
	]
))

WS.verifyResponseStatusCode(postResponse, 200)

// Get the actual generated ID from POST response
def createdId = WS.getElementPropertyValue(postResponse, 'id')
println "Created Pet ID: " + createdId

// Verify only name + status (ID is generated by API)
WS.verifyElementPropertyValue(postResponse, 'name', name)
WS.verifyElementPropertyValue(postResponse, 'status', status)


// GET request using the generated ID
def getResponse = WS.sendRequest(findTestObject(
	'usingdata/getpetdata',
	[
		('id') : createdId
	]
))

WS.verifyResponseStatusCode(getResponse, 200)

// Validate API data from GET
WS.verifyElementPropertyValue(getResponse, 'id', createdId)
WS.verifyElementPropertyValue(getResponse, 'name', name)
WS.verifyElementPropertyValue(getResponse, 'status', status)
